# @Author: Massimo De Mauri <massimodemauri>
# @Date:   2019-02-06T15:13:09+01:00
# @Email:  massimo.demauri@kuleuven.be
# @Project: OpenBB
# @Filename: Project.toml
# @Last modified by:   massimo
# @Last modified time: 2019-03-03T19:18:56+01:00
# @License: apache 2.0


name = "OpenBB"
uuid = "fbd8be30-2a18-11e9-3ccc-6baa3bf8db03"
authors = ["massimo.demauri@kuleuven.be <massimo.demauri@kuleuven.be>"]
version = "0.1.0"

[deps]
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OSQP = "ab2f91bb-94b4-55e3-9ba0-7f65df51de79"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
